sp:
  user-service:
    users: "[{\"id\":99, \"username\":\"abc99\",\"password\":\"111\"},{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
  instance:
    prefer-ip-address: true #显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} #显示格式 
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh

